#!/bin/bash
cd $(dirname $(dirname $0)) || exit

docker compose exec $COMPOSE_EXEC_FLAGS site /bin/bash -c "\
    bash make_style.sh && \
    python3 manage.py collectstatic --noinput && \
    python3 manage.py compilemessages && \
    python3 manage.py compilejsi18n && \
    cp -r resources/ /assets/ && \
    rm -r resources/dark resources/martor-description.css resources/style.css resources/vars.scss && \
    rm -r sass_processed && \
    cp 502.html /assets/ && \
    cp logo.png /assets/ && \
    cp robots.txt /assets/"
